# Generated by Django 5.1.6 on 2025-06-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit_app.ciudad'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit_app.departamento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit_app.estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idServicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit_app.servicios'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodoDePago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit_app.metodo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit_app.pais'),
        ),
    ]
