# Generated by Django 5.1.6 on 2025-06-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='idEstado',
        ),
    ]
