# Generated by Django 5.1.6 on 2025-06-05 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0002_remove_reserva_idestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doit_app.pais'),
        ),
    ]
