# Generated by Django 5.1.6 on 2025-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0002_alter_reserva_ciudad_alter_reserva_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Ciudad',
            field=models.CharField(choices=[('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Departamento',
            field=models.CharField(choices=[('Cundinamarca', 'Cundinamarca'), ('Antioquia', 'Antioquia'), ('Valle del Cauca', 'Valle del Cauca')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idEstado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodoDePago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pais',
            field=models.CharField(choices=[('Colombia', 'Colombia'), ('Perú', 'Perú'), ('México', 'México')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='reserva',
            table=None,
        ),
    ]
