# Generated by Django 5.1.6 on 2025-06-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0003_alter_reserva_options_alter_reserva_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='Duracion',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='Precio',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='Ubicacion',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='idCiudad',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='idPagos',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='idestado',
        ),
    ]
