# Generated by Django 5.2.1 on 2025-05-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre'], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='numDoc',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('experto', 'Experto')], default='usuario', max_length=20),
        ),
    ]
