# Generated by Django 5.2.1 on 2025-05-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_genero_options_alter_customuser_numdoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Usuario Normal'), ('experto', 'Experto')], default='usuario', max_length=20),
        ),
    ]
